version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - bash build.sh test
      - bash build.sh package
artifacts:
  type: zip
  files:
    - template-export.yml
